### ISSUE TITLE
Setup CD

### ISSUE THREAD

**Issue by carryall** [carryall/react-survey-challenge#3]
## Why

To align with Nimble's workflow and ensure the effectiveness of the product delivery we should have automated CD

## Acceptance Criteria

- [ ] Setup CD on Github Action to deploy on [Netlify](https://www.netlify.com/)

**Comment by hoangmirs** [comment]
@carryall I think for this SPA, we can use Netlify or Vercel to deploy, then we can get the preview build on each PR.
If you want that feature, you can give it a try 💪

**Comment by carryall** [comment]
> @carryall I think for this SPA, we can use Netlify or Vercel to deploy, then we can get the preview build on each PR. If you want that feature, you can give it a try 💪

Thanks @hoangmirs I think I'll try Netlify
